import { CmsCard } from "@/components/cms-card";
import { ComparisonTable } from "@/components/comparison-table";
import { projects } from "@/components/cms-data";


const navLinks = ["Home", "CMS Projects", "Tech Stack", "My Projects", "About"];

export default function Home() {
  return <main className="overflow-hidden bg-white">
    <header className="sticky top-0 z-30 border-b border-white/70 bg-white/80 backdrop-blur-xl"><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-6 lg:px-8" aria-label="Main navigation">
      <a href="#home" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-ink text-lg font-black text-white shadow-lg shadow-ink/15">C</span><span className="text-base font-extrabold tracking-tight text-ink">CMS<span className="text-violet">.hub</span></span></a>
      <div className="hidden items-center gap-7 lg:flex">{navLinks.map((item) => <a href={`#${item.toLowerCase().replaceAll(" ", "-")}`} key={item} className="text-sm font-semibold text-slate transition hover:text-violet">{item}</a>)}</div>
      <a href="#cms-projects" className="rounded-xl bg-ink px-4 py-2.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-violet">Explore stacks</a>
    </nav></header>

    <section id="home" className="hero-grid relative"><div className="absolute left-1/2 top-0 -z-10 h-[560px] w-[760px] -translate-x-1/2 rounded-full bg-[#EEEAFF] blur-3xl" />
      <div className="mx-auto grid max-w-7xl items-center gap-14 px-6 py-20 sm:py-28 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-32">
        <div className="max-w-2xl"><p className="inline-flex items-center gap-2 rounded-full border border-[#DDD6FF] bg-white/90 px-4 py-2 text-xs font-bold uppercase tracking-[0.14em] text-violet shadow-sm"><span className="h-1.5 w-1.5 rounded-full bg-violet" /> Headless CMS workspace</p>
          <h1 className="mt-7 text-5xl font-extrabold leading-[1.02] tracking-[-0.055em] text-ink sm:text-6xl lg:text-7xl">Content<br />Management<br /><span className="text-violet">System.</span></h1>
          <p className="mt-6 max-w-xl text-base leading-7 text-slate sm:text-lg">Compare three powerful headless CMS platforms, their technology stacks, and the Microcontroller lecture reports assigned to each project.</p>
          <div className="mt-9 flex flex-wrap gap-3"><a href="#cms-projects" className="inline-flex items-center gap-2 rounded-xl bg-violet px-6 py-3.5 text-sm font-bold text-white shadow-lg shadow-violet/25 transition hover:-translate-y-0.5 hover:bg-[#5737E6]">View projects <span aria-hidden="true">↓</span></a><a href="#my-projects" className="inline-flex items-center gap-2 rounded-xl border border-line bg-white px-6 py-3.5 text-sm font-bold text-ink shadow-sm transition hover:border-violet hover:text-violet">View reports <span aria-hidden="true">→</span></a></div>
          <div className="mt-11 flex flex-wrap gap-7 border-t border-line pt-6"><Stat value="03" label="CMS platforms" /><Stat value="07" label="LEC reports" /><Stat value="01" label="Dashboard" /></div>
        </div>
        <DashboardPreview />
      </div>
    </section>

    <section id="cms-projects" className="bg-mist py-20 sm:py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><SectionHeading eyebrow="CMS projects" title="Choose your content engine." description="Each platform has its own modern technology stack and its assigned Microcontroller LEC topics." /><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{projects.map((project) => <CmsCard key={project.name} project={project} />)}</div><div className="mt-10 text-center"><a href="#my-projects" className="inline-flex items-center gap-2 rounded-xl border border-violet bg-white px-6 py-3.5 text-sm font-bold text-violet shadow-sm transition hover:-translate-y-0.5 hover:bg-violet hover:text-white">Explore my reports <span aria-hidden="true">→</span></a></div></div></section>
    <section id="tech-stack" className="mx-auto max-w-7xl px-6 py-20 sm:py-24 lg:px-8"><div className="mb-10 text-center"><p className="text-sm font-bold uppercase tracking-[0.14em] text-violet">At a glance</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-ink sm:text-4xl">Compare the stacks.</h2><p className="mt-3 text-slate">The core technologies powering every CMS project.</p></div><ComparisonTable /></section>
    <section id="my-projects" className="relative bg-ink py-20 text-white sm:py-24"><div className="absolute inset-0 opacity-20 [background-image:radial-gradient(#fff_1px,transparent_1px)] [background-size:22px_22px]" /><div className="relative mx-auto max-w-7xl px-6 lg:px-8"><SectionHeading dark eyebrow="My projects" title="Microcontroller (LEC) reports." description="Lecture topics organized according to their CMS project." /><div className="grid gap-5 md:grid-cols-3">{projects.map((project) => <article key={project.name} className="rounded-[22px] border border-white/10 bg-white/[0.07] p-6 backdrop-blur-sm transition duration-300 hover:-translate-y-1 hover:bg-white/[0.11]"><div className="flex items-center justify-between"><span className="inline-flex rounded-lg px-3 py-1.5 text-xs font-extrabold tracking-[0.12em]" style={{ backgroundColor: project.accentSoft, color: project.accent }}>{project.name}</span><span className="text-xs font-bold text-white/55">{project.lectureTopics.length} reports</span></div><h3 className="mt-6 text-xl font-bold tracking-tight">Assigned lecture reports</h3><ul className="mt-5 space-y-3">{project.lectureTopics.map((report, index) => <li key={report} className="flex items-center gap-3 rounded-xl bg-white/[0.08] px-3.5 py-3 text-sm font-semibold"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-md bg-white/10 text-xs font-bold" style={{ color: project.accent }}>{String(index + 1).padStart(2, "0")}</span>{report}</li>)}</ul></article>)}</div></div></section>
    <footer id="about" className="bg-[#101827] text-white/60"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-6 py-9 text-sm sm:flex-row sm:items-center sm:justify-between lg:px-8"><span className="font-semibold text-white">CMS<span className="text-[#BEB2FF]">.hub</span> <span className="ml-2 font-normal text-white/50">CMS Projects Dashboard</span></span><span>David, Lance B. · Microcontroller (LEC)</span></div></footer>
  </main>;
}

function Stat({ value, label }: { value: string; label: string }) { return <div><p className="text-2xl font-extrabold tracking-tight text-ink">{value}</p><p className="mt-1 text-xs font-semibold uppercase tracking-[0.1em] text-slate">{label}</p></div>; }
function SectionHeading({ eyebrow, title, description, dark = false }: { eyebrow: string; title: string; description: string; dark?: boolean }) { return <div className="mb-11 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className={`text-sm font-bold uppercase tracking-[0.14em] ${dark ? "text-[#BEB2FF]" : "text-violet"}`}>{eyebrow}</p><h2 className={`mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl ${dark ? "text-white" : "text-ink"}`}>{title}</h2></div><p className={`max-w-sm text-sm leading-6 ${dark ? "text-white/65" : "text-slate"}`}>{description}</p></div>; }
function DashboardPreview() { return <div className="relative mx-auto w-full max-w-[510px]"><div className="absolute -inset-5 -z-10 rounded-[40px] bg-gradient-to-br from-violet/20 via-transparent to-[#36C8A4]/20 blur-2xl" /><div className="overflow-hidden rounded-[28px] border border-white/80 bg-white p-4 shadow-[0_30px_80px_rgba(34,24,87,.18)] sm:p-5"><div className="flex items-center justify-between border-b border-line pb-4"><div className="flex gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-[#F3796A]" /><span className="h-2.5 w-2.5 rounded-full bg-[#F5C658]" /><span className="h-2.5 w-2.5 rounded-full bg-[#5CCB86]" /></div><span className="rounded-full bg-mist px-3 py-1 text-[10px] font-bold uppercase tracking-[0.12em] text-slate">Overview</span></div><div className="pt-5"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate">Project status</p><p className="mt-1 text-2xl font-extrabold tracking-tight text-ink">All systems ready</p></div><span className="rounded-full bg-[#E9FAF4] px-3 py-1.5 text-xs font-bold text-[#0B8A62]">Live</span></div><div className="mt-5 grid grid-cols-3 gap-3">{projects.map((project) => <div key={project.name} className="rounded-2xl border border-line p-3"><span className="grid h-8 w-8 place-items-center rounded-lg text-sm font-black" style={{ backgroundColor: project.accentSoft, color: project.accent }}>{project.mark}</span><p className="mt-5 text-xs font-bold text-ink">{project.name}</p><div className="mt-2 h-1.5 rounded-full bg-mist"><div className="h-1.5 rounded-full" style={{ width: "78%", backgroundColor: project.accent }} /></div></div>)}</div><div className="mt-5 rounded-2xl bg-ink p-5 text-white"><div className="flex items-center justify-between"><p className="text-sm font-bold">Microcontroller LEC</p><span className="text-xs text-white/60">7 reports</span></div><div className="mt-4 flex gap-2"><span className="rounded-lg bg-white/10 px-2.5 py-1.5 text-xs font-semibold">History</span><span className="rounded-lg bg-white/10 px-2.5 py-1.5 text-xs font-semibold">SAP</span><span className="rounded-lg bg-white/10 px-2.5 py-1.5 text-xs font-semibold">RasPi</span></div></div></div></div></div>; }
